---
title: "Interactive Data Story - Group Six"
author: "Annie Staker, Edgar Lopez, Scott Fry" [FIXME should we include Srimant and Cat here since we describe both the interaction data story and the Shiny app here?]
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Introduction to the problem and description of data available

In this project we sought to understand whether bias existed in US faculty 
salary data on the basis of sex. To do this, we sought to answer four questions: 

1. Did sex bias exist at the university in the 1995?
2. Has sex bias existed in the starting salaries of faculty members (salaries in 
the year hired)?
3. Has sex bias existed in granting salary increases between 1990 -1995?
4. Has sex bias existed in granting promotions from Associate to full Professor?

The data set includes information on faculty employed at a university in 1995. 
The data set includes monthly salary, sex, a unique faculty member identifier, 
information on highest degree attained, year highest degree was attained, field, 
start year, rank, and whether the faculty member has an administrative role. The
monthly salary, rank and whether the faculty member has an administrative role may
vary by year, all other variables will be consistent across a faculty member for all
of their records.

## Methods

To address these questions, we developed two deliverables: an interactive web 
application and an interactive data story. The interactive web application was 
written using RShiny and answers Question 3. It is available 
[here (FIXME)](https://website-name.com). Data stories were written for 
Questions 1, 2, and 4 and are included in the Results section below.

## Results

Present results for each scientific question
- Interactive Data Stories Go Here

The results presented in this section are interactive data stories for Questions 
1, 2, and 4. The results and summary for Question 3 are part of the interactive 
web application.

### Question 1

We want to answer the question, "Did sex bias exist at the university in the 
1995?"

### Question 2

### Question 4

## Summary

Summarize the findings
